// <auto-generated />
namespace GiveIT.UI.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class volunteer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(volunteer));
        
        string IMigrationMetadata.Id
        {
            get { return "201307181934163_volunteer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
